### ISSUE TITLE
pool 0.1.4.3 release checklist

### ISSUE THREAD

**Issue by wch** [rstudio/pool#92]
- [x] If not a new package, make sure any warnings/errors in CRAN check results page are fixed
- [x] Build and check on Centos 6. (might need [this](https://github.com/rstudio/websocket/wiki/Installing-on-CentOS-6))
- [x] Create RC branch `rc-v0.1.4.3`
- [x] Change the DESCRIPTION and NEWS on this branch to change the version number to the desired version for CRAN
- [x] Clean your package directory to remove any extraneous files, including ones that are git-ignored. (Warning, this will delete any unsaved buffers in RStudio! Also, be sure to close RStudio before taking this step!) `git clean -xdi .`
- [x] Build your package with `R CMD build`
- [x] Do a sanity check by installing/testing the built package.
- [x] Perform revdep check using https://github.com/r-lib/revdepcheck, if this is not the initial CRAN release.
- [x] Run `R CMD check --as-cran pkg_version.tar.gz` both locally and on win-builder. You can also use https://r-hub.github.io/rhub/.
- [x] Review CRAN Policies document
- [x] Submit to CRAN via their online form.
- [x] When accepted, tag the RC branch with a v0.1.4.3 tag (or whatever version you finally ended up getting accepted), and push the tag to origin.
- [x] Merge RC into master.
- [x] On master, change the package version to 0.1.4.3.9000.
